name: CI Actions

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        build_type: [Debug, Release]
        compiler: [g++, clang++]
        opts: [coverage, asan, tsan, usan, common]
        exclude:
        - build_type: Release
          opts: coverage
        - build_type: Release
          opts: asan
        - build_type: Release
          opts: tsan
        - build_type: Release
          opts: usan
        - build_type: Debug
          opts: common
        - build_type: Debug
          opts: tsan
        - build_type: Debug
          compiler: g++
          opts: asan

    name: ${{ matrix.os }} ${{ matrix.build_type }} ${{ matrix.compiler }} ${{ matrix.opts }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install toolset
        run: |
          sudo apt-get -y install software-properties-common && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends g++-14 clang-18 clang-format-18 clang-tidy-18 lcov llvm doxygen graphviz python3-pip
          sudo ln -s $(which g++-14) /usr/local/bin/g++
          sudo ln -s $(which gcc-14) /usr/local/bin/gcc
          sudo ln -s $(which gcov-14) /usr/local/bin/gcov
          sudo ln -s $(which clang++-18) /usr/local/bin/clang++
          sudo ln -s $(which clang-18  ) /usr/local/bin/clang
          sudo ln -s $(which llvm-cov-18) /usr/local/bin/llvm-cov
          sudo ln -s $(which clang-tidy-18) /usr/local/bin/clang-tidy
          pip install conan==2.17.1 cmake==3.29.2
          uname -a
          g++ --version
          clang++ --version

      - name: Conan cache
        uses: actions/cache@v4
        with:
          path: build/.conan2
          key: conan-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.compiler }}-${{ matrix.opts }}-${{ hashFiles('conanfile.py', 'scripts/conan/*') }}

      - name: Conan install
        run: ./scripts/conan/build.sh ${{ matrix.build_type }} ${{ matrix.compiler }} ${{ matrix.opts }} build install

      - name: Conan build
        run: ./scripts/conan/build.sh ${{ matrix.build_type }} ${{ matrix.compiler }} ${{ matrix.opts }} build build

      - name: Upload coverage reports to Codecov
        if: matrix.opts == 'coverage'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: build/coverage
          name: ${{ matrix.build_type }} ${{ matrix.compiler }}
